In [1]:
import pandas as pd
import sklearn
import numpy as np

In [2]:
location = 'data/'
featuresFile = location + 'features.csv'
labelsFile = location + 'labels.csv'
targetFile = location + 'target_competencia_ids.csv'
featuresPredictFile = location + 'FeaturesFiltrado7.csv'

In [3]:
dtypeFeatures = {
    'device_id': 'str',
    'eventsCount': 'float64',
    'eventsMostFreqDay': 'float64',
    'eventsMeanInterval': 'float64',
    'eventsAproxFreq': 'float64',
    'eventsStdDevInterval': 'float64',
    'eventsLast': 'float64',
    'installsCount': 'float64',
    'installsMostFreqDay': 'float64',
    'installsMeanInterval': 'float64',
    'installsAproxFreq': 'float64',
    'installsStdDevInterval': 'float64',
    'installsLast': 'float64',
    'clicksCount': 'float64',
    'clicksMostFreqDay': 'float64',
    'clicksMeanInterval': 'float64',
    'clicksAproxFreq': 'float64',
    'clicksStdDevInterval': 'float64',
    'clicksLast': 'float64',
    'auctionsCount': 'float64',
    'auctionsMostFreqDay': 'float64',
    'auctionsMeanInterval': 'float64',
    'auctionsAproxFreq': 'float64',
    'auctionsStdDevInterval': 'float64',
    'auctionsLast': 'float64'
}
dtypeLabels = {
    'device_id': 'str',
    'st': 'float64',
    'sc': 'float64'
}
dtypeTarget = {
    'ref_hash': 'str',
    'obj': 'float64',
}

In [4]:
features = pd.read_csv(featuresFile, usecols=dtypeFeatures.keys(), dtype=dtypeFeatures)
labels = pd.read_csv(labelsFile, usecols=dtypeLabels.keys(), dtype=dtypeLabels)

In [5]:
labels = labels.sort_values(by='device_id').reset_index(drop=True)

In [6]:
features = features.sort_values(by='device_id').reset_index(drop=True)

In [7]:
labels = labels.drop('device_id', axis=1)

In [8]:
featuresPredict = pd.read_csv(featuresPredictFile, usecols=dtypeFeatures.keys(), dtype=dtypeFeatures)
target = pd.read_csv(targetFile, usecols=dtypeTarget.keys(), dtype=dtypeTarget)

In [9]:
target['device_id'] = target['ref_hash'].str[:-3]
target = target.drop('ref_hash', axis=1)
target = target.drop_duplicates(subset='device_id')

In [10]:
labels=labels.fillna(259200)

In [11]:
features=features.fillna(0)
features.loc[features['installsAproxFreq'] == float('inf'), 'installsAproxFreq'] = 0

In [12]:
featuresPredict = featuresPredict.fillna(0)
featuresPredict.loc[featuresPredict['installsAproxFreq'] == float('inf'), 'installsAproxFreq'] = 0

In [13]:
featuresPredict=featuresPredict.drop('device_id',axis=1)

Prediccion ST

In [30]:
labelsST=labels['st']

In [31]:
labelsST.head()

0    259200.000000
1    259200.000000
2    184052.302630
3     97652.302630
4     24628.726364
Name: st, dtype: float64

In [32]:
X = features
X = X.drop('device_id', axis=1)
y = labelsST

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, random_state=0)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)   

((1561138, 24), (1561138,))
((173460, 24), (173460,))


In [34]:
from sklearn.linear_model import Ridge
RidgeModel=Ridge(alpha=0.1)
RidgeModel.fit(X,y)
ridge_predictST=RidgeModel.predict(featuresPredict)

In [35]:
from sklearn import linear_model
lasso = linear_model.Lasso(alpha=0.1)
lasso.fit(X,y)  
lasso_predictST=lasso.predict(featuresPredict)

/home/nicolas/.local/lib/python2.7/site-packages/sklearn/linear_model/coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)


In [36]:
#from sklearn.metrics import mean_squared_error
#mean_squared_error(y_test, ridge_predict)

In [51]:
pd.Series(abs(ridge_predictST)).to_csv('data/StPredict.csv')

In [38]:
ridge_predictST

array([270425.60119626, 190428.81671646, 411182.96317203, ...,
       -53051.95043335,  39814.53681827, 489517.57540767])

In [48]:
lasso_predictST

array([270778.5622502 , 190357.62499454, 411531.73041078, ...,
       -52708.62728643,  40073.2968312 , 489709.23174157])

Predicciones SC

In [39]:
labelsSC=labels['sc']

In [40]:
X = features
X = X.drop('device_id', axis=1)
y = labelsSC

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, random_state=0)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)   

((1561138, 24), (1561138,))
((173460, 24), (173460,))


In [42]:
from sklearn.linear_model import Ridge
RidgeModel=Ridge(alpha=0.1)
RidgeModel.fit(X,y)
ridge_predictSC=RidgeModel.predict(featuresPredict)

In [43]:
from sklearn import linear_model
lasso = linear_model.Lasso(alpha=0.1)
lasso.fit(X,y)  
lasso_predictSC=lasso.predict(featuresPredict)

In [44]:
#from sklearn.metrics import mean_squared_error
#mean_squared_error(y_test, ridge_predict)

In [52]:
pd.Series(abs(ridge_predictSC)).to_csv('data/ScPredict.csv')

In [46]:
ridge_predictSC

array([396540.45039023, 248307.07915095, 591340.50515063, ...,
       152517.30357805, 234772.01849293, 686942.35336699])

In [47]:
lasso_predictSC

array([397008.50878411, 248226.21268036, 591799.43389876, ...,
       152905.54006814, 235066.30866803, 687237.15494432])

In [79]:
def funcionMistica(lista1,lista2,lista3):
    a=[]
    for i in range(len(lista1)):
        a.append((str(lista3[i])+'_st',lista1[i]))
        a.append((str(lista3[i])+'_sc',lista2[i]))
    return a

In [50]:
abs(ridge_predictST)

array([270425.60119626, 190428.81671646, 411182.96317203, ...,
        53051.95043335,  39814.53681827, 489517.57540767])

In [83]:
predicciones=pd.DataFrame(funcionMistica(abs(ridge_predictST),abs(ridge_predictSC),list(target['device_id'])))#.to_csv('data/prediccionesConcat.csv',index=False)

In [88]:
predicciones=predicciones.rename(columns={0:'ref_hash',1:'obj'})

In [89]:
predicciones.to_csv('data/prediccionesConcat.csv',index=False)